'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CartoonersFileViewerProgram.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cartooners&apos; File Formats, by: Peter Swinkels ***2015***
        '''
        '''[General Program Information]
        '''Cartooners 1988/1989 - by: Electronic Arts &amp; IDTA
        '''
        '''Note:
        '''This document applies to the game&apos;s MS-DOS version.
        '''
        '''===================================================================================================
        '''
        '''[Animated Actors]
        '''
        '''[File Information]
        '''Endianess: little.
        '''Extension: *.act
        '''
        '''[File Layout]
        '''Begin Structure: Header.
        '''	0x00	BYTE		Null. ***
        '''	0x01	0x03 BYTES	Is used to check if the file is valid. *** [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Cartooners_File_Formats() As String
            Get
                Return ResourceManager.GetString("Cartooners_File_Formats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cartooners File Viewer - Help
        '''
        '''[About Cartooners]
        '''Note: this is not meant to be a complete description. See the manual that comes with this program if you want to know more.
        '''
        '''Cartooners is a basic animation software package originally developed for the Apple IIGS by ITDA and published by Electronic Arts in 1987 primarily aimed at children. It has also been ported to run under MS-DOS among others. With Cartooners the user can make a simple animated movie by placing static or animated actors over optiona [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Cartooners_File_Viewer_Help() As String
            Get
                Return ResourceManager.GetString("Cartooners_File_Viewer_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About text.;208116;226
        '''A new actor.;215471;12
        '''Button edge style information.;205686;38
        '''C_FILE_INFO.;222823;11
        '''Clear/erase text.;205466;45
        '''Day and month abbreviations.;225300;58
        '''Default speech balloon information.;156277;1079
        '''Dialog text.;211620;790
        '''Drive letters.;205724;84
        '''Exclamation speech balloon information.;158825;2049
        '''80286+ executable code.;0;156224
        '''Executable extensions.;225116;15
        '''File system related characters.;206799;23
        '''File extensions.;204291;29
        '''Invalid actor message.;215322;53
        '''Key [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Data_Cartooners_Chunks() As String
            Get
                Return ResourceManager.GetString("Data_Cartooners_Chunks", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
